spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: "true"
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.DerbyDialect"
  database:
    driverClassName: "org.apache.derby.jdbc.ClientDriver"
  datasource:
    url: "jdbc:derby://localhost:1527/itemsharingdatabase"
    username: "root"
    password: "{cipher}"
    testWhileIdle: "true"
    validationQuery: "SELECT 1"
    
security:
  basic:
    enabled: false
    
server:
  port: 8081
 

 