spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: "true"
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQL5Dialect" 
  database:
    driverClassName: "com.mysql.jdbc.Driver"
  datasource:
    url: "jdbc:mysql://localhost:3306/itemsharingdatabase"
    username: "root"
    password: "{chiper}41f56dea44cc63a910c994a51bd5c612ea64b5662d96398278dc3cf5813cdfb1"
    testWhileIdle : "true"
    validation-query: "SELECT 1"
      
security:
  basic:
    enabled: false   
    
server:
  port: 8081     
  
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone:http://localhost:8761/eureka/  
